GET http://localhost:5000/users HTTP/1.1
###

GET http://localhost:5000/users/2 HTTP/1.1
###

POST http://localhost:5000/register HTTP/1.1
content-type: application/json

{ 
    "email": "test@tv.za",
    "password": "w1234567"
}
###

POST http://localhost:5000/login HTTP/1.1
content-type: application/json

{ 
    "email": "crema@tv.za",
    "password": "w123"
}
###

GET http://localhost:5000/bookings HTTP/1.1
###

GET http://localhost:5000/users/1/bookings HTTP/1.1
###

GET http://localhost:5000/listings HTTP/1.1
###

POST http://localhost:5000/users HTTP/1.1
content-type: application/json

{ 
    "name": "kkk zitha", 
    "email": "kkkz@christ.io",
    "password": "12378921"
}



