export const LISTING_LIST_REQUEST = "LISTING_LIST_REQUEST";
export const LISTING_LIST_SUCCESS = "LISTING_LIST_SUCCESS";
export const LISTING_LIST_FAIL = "LISTING_LIST_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";